# Generated by Django 4.2.7 on 2023-12-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_category_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categories',
        ),
    ]
