# Generated by Django 4.2.7 on 2023-12-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_category_postcategory_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categories',
            new_name='category',
        ),
    ]
